spring.application.name=sping-rest-demo
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=postgres
spring.datasource.password=teamkuneho



#logging.level.root=warn
#spring.main.banner-mode=off
#
#logging.level.org.hibernate.sql=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.hibernate.ddl-auto=update